<a href="https://colab.research.google.com/github/abhishekatujjain/Tensorflow/blob/main/00_TF_Funda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [ ]:
#creating tensors
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimension fo tensor
scalar.ndim

0

In [ ]:
#create a vector 
vector = tf.constant([10, 10])
print(vector)
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1
tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [ ]:
# create a matrix
matrix = tf.constant([ [10, 7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
 matrix.ndim

2

In [ ]:
another_matrix  = tf.constant([ [10., 7.], [3., 2.,], [8., 9.,]], dtype = tf.float16)
another_matrix
# we used smaller datatype instead of int32 of 32 bits to 16 bits of float, if we need more memory, change dtype

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# create a tensor, another_matrix is of 2 dimension
tensor = tf.constant([[ [1, 2, 3],
                        [4,5,6]],
                       [[7,8,9],
                        [10, 11, 12]],
                        [[13, 14, 15], [16, 17, 18]
                       ]])
print(tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
tensor.ndim

3

In [ ]:
#creating tensorflow variable
changeble = tf.Variable([[1, 2],
                         [2, 1]])
unchangeble = tf.constant([[1, 2],
                         [2, 1]])
changeble, unchangeble

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[1, 2],
        [2, 1]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 1]], dtype=int32)>)

In [ ]:
# to update changeble but can not unchangeble becoz it is constant
changeble[0, 0].assign(10)
changeble

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  2],
       [ 2,  1]], dtype=int32)>

In [ ]:
#creating random tensors
# used for intializing weights
random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducebility
random_1 = random_1.normal(shape =(3,2))  # normally distributed
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape = (3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
# shuffling the tensors. Used where order doesn't matters
not_shuffled = tf.constant([ [1,2],
                            [3, 4],
                            [5,6] ])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed = 12)  # operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed = 12)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
# applying global level seed
tf.random.set_seed(12)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.set_seed(12)
tf.random.shuffle(not_shuffled)  # shuffled but result not changed for global one

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.set_seed(12)
tf.random.shuffle(not_shuffled, seed = 12)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.set_seed(12)
tf.random.shuffle(not_shuffled, seed = 12)  # order not changed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [ ]:
# another way to create tensors
print(tf.ones([3,3]))
print(tf.zeros(shape = (3,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
# turn NumPy arrays into tensors
# Usually, NumPy arrays and TensorFlow tensors are same, except, tensors runs faster on GPU
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A, shape = (2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
#getting information from tensors
rank_4_tensor = tf.zeros(shape= [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#get various attributes of tensor
print("Data type:", rank_4_tensor.dtype)
print("No of dimensions (rank)", rank_4_tensor.ndim)
print("Shape of Tensor", rank_4_tensor.shape)
print("Elements along 0 axis", rank_4_tensor.shape[0])
print('Elements along last axis', rank_4_tensor.shape[-1])
print('Total no of elemenst in tensor', tf.size(rank_4_tensor))
print('Total no of elemenst in tensor', tf.size(rank_4_tensor).numpy())

Data type: <dtype: 'float32'>
No of dimensions (rank) 4
Shape of Tensor (2, 3, 4, 5)
Elements along 0 axis 2
Elements along last axis 5
Total no of elemenst in tensor tf.Tensor(120, shape=(), dtype=int32)
Total no of elemenst in tensor 120


Indexing the tensors

In [ ]:
# get first two elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the second last one
rank_4_tensor[:1, :1, :, :1]


<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
import numpy as np
import tensorflow as tf
npary = np.arange(1, 121, dtype = np.int32)
npary

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120], dtype=int32)

In [ ]:
rnk4tensor = tf.constant(npary, shape = (2,3,4, 5))
rnk4tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]], dtype=int32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rnk4tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[1, 2, 3, 4, 5]]]], dtype=int32)>

In [ ]:
# Get the first element from each dimension from each index except for the second last one
rnk4tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 6],
         [11],
         [16]]]], dtype=int32)>

In [ ]:
rnk4tensor[:2, :1, :1, :]

<tf.Tensor: shape=(2, 1, 1, 5), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4,  5]]],


       [[[61, 62, 63, 64, 65]]]], dtype=int32)>

In [ ]:
rnk4tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=int32, numpy=
array([[[[ 1]]],


       [[[61]]]], dtype=int32)>

In [ ]:
rnk4tensor[:, :3, :1, :1]

<tf.Tensor: shape=(2, 3, 1, 1), dtype=int32, numpy=
array([[[[  1]],

        [[ 21]],

        [[ 41]]],


       [[[ 61]],

        [[ 81]],

        [[101]]]], dtype=int32)>

In [ ]:
#adding extra diemsion in rnk4tensor

#lets create rank 2 tensor
rank2tensor = tf.constant([[1,2],
                           [3,4]])
rank2tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# get the last item of each row
rank2tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# now add extra diemsion
rank3tensor = rank2tensor[..., tf.newaxis]  # ... means all the previous axis [:, :, tf.newaxis]
rank3tensor  # so we got new axis, rows =1

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
#another way
tf.expand_dims(rank2tensor, axis = -1) # -1 expand the final axis  # only 1 column is output

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank2tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank2tensor, axis = 1)  # only 1 row in output

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

In [ ]:
# tensor remains same
rank2tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

# Manipulating the Tensors

In [ ]:
# Basic Operations, like add, substract.... python operations

tensor = tf.constant([[1, 2],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
# but original tensor remains unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
# multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Alternative we can use tf library functions
tf.multiply(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

When we use tensor lib operations, it works fast on GPU

In [ ]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 22],
       [23, 24]], dtype=int32)>

In [ ]:
tf.math.add(tensor, 10)  #same

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 22],
       [23, 24]], dtype=int32)>

Matrix Multiplication

In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[277, 300],
       [325, 352]], dtype=int32)>

In [ ]:
 tensor * tensor   # element wise

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121, 144],
       [169, 196]], dtype=int32)>

In [ ]:
tensor @ tensor # python matrix multiplication 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[277, 300],
       [325, 352]], dtype=int32)>

In [ ]:
a = tf.reshape( tensor, (1,4))
a

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[11, 12, 13, 14]], dtype=int32)>

In [ ]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8], [9, 10], [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

# Dot Product
***either use tf.matmult or tf.tensordot***


In [ ]:
tf.tensordot(tf.transpose(X), Y, axes =1)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes =0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[21, 24],
         [27, 30],
         [33, 36]],

        [[35, 40],
         [45, 50],
         [55, 60]]],


       [[[14, 16],
         [18, 20],
         [22, 24]],

        [[28, 32],
         [36, 40],
         [44, 48]],

        [[42, 48],
         [54, 60],
         [66, 72]]]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes =0).shape

TensorShape([2, 3, 3, 2])

In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

# Changing the Tensor Data Type

In [5]:
import tensorflow as tf
#create a tensor with default datatype
B = tf.constant([1.2, 2.3])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 2.3], dtype=float32)>

In [6]:
C = tf.constant([7, 10])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [7]:
#change float32 to float16
D = tf.cast(B, dtype= tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 2.3], dtype=float16)>

In [9]:
E = tf.cast(C, dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

# Aggregating Tensors