<a href="https://colab.research.google.com/github/abhishekatujjain/Tensorflow/blob/main/00_TF_Funda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [ ]:
#creating tensors
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimension fo tensor
scalar.ndim

0

In [ ]:
#create a vector 
vector = tf.constant([10, 10])
print(vector)
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1
tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [ ]:
# create a matrix
matrix = tf.constant([ [10, 7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
 matrix.ndim

2

In [ ]:
another_matrix  = tf.constant([ [10., 7.], [3., 2.,], [8., 9.,]], dtype = tf.float16)
another_matrix
# we used smaller datatype instead of int32 of 32 bits to 16 bits of float, if we need more memory, change dtype

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# create a tensor, another_matrix is of 2 dimension
tensor = tf.constant([[ [1, 2, 3],
                        [4,5,6]],
                       [[7,8,9],
                        [10, 11, 12]],
                        [[13, 14, 15], [16, 17, 18]
                       ]])
print(tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
tensor.ndim

3

In [ ]:
#creating tensorflow variable
changeble = tf.Variable([[1, 2],
                         [2, 1]])
unchangeble = tf.constant([[1, 2],
                         [2, 1]])
changeble, unchangeble

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[1, 2],
        [2, 1]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 1]], dtype=int32)>)

In [ ]:
# to update changeble but can not unchangeble becoz it is constant
changeble[0, 0].assign(10)
changeble

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  2],
       [ 2,  1]], dtype=int32)>

In [ ]:
#creating random tensors
# used for intializing weights
random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducebility
random_1 = random_1.normal(shape =(3,2))  # normally distributed
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape = (3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
# shuffling the tensors. Used where order doesn't matters
not_shuffled = tf.constant([ [1,2],
                            [3, 4],
                            [5,6] ])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed = 12)  # operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed = 12)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
# applying global level seed
tf.random.set_seed(12)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.set_seed(12)
tf.random.shuffle(not_shuffled)  # shuffled but result not changed for global one

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.set_seed(12)
tf.random.shuffle(not_shuffled, seed = 12)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.set_seed(12)
tf.random.shuffle(not_shuffled, seed = 12)  # order not changed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [ ]:
# another way to create tensors
print(tf.ones([3,3]))
print(tf.zeros(shape = (3,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
# turn NumPy arrays into tensors
# Usually, NumPy arrays and TensorFlow tensors are same, except, tensors runs faster on GPU
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A, shape = (2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
#getting information from tensors
rank_4_tensor = tf.zeros(shape= [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#get various attributes of tensor
print("Data type:", rank_4_tensor.dtype)
print("No of dimensions (rank)", rank_4_tensor.ndim)
print("Shape of Tensor", rank_4_tensor.shape)
print("Elements along 0 axis", rank_4_tensor.shape[0])
print('Elements along last axis', rank_4_tensor.shape[-1])
print('Total no of elemenst in tensor', tf.size(rank_4_tensor))
print('Total no of elemenst in tensor', tf.size(rank_4_tensor).numpy())

Data type: <dtype: 'float32'>
No of dimensions (rank) 4
Shape of Tensor (2, 3, 4, 5)
Elements along 0 axis 2
Elements along last axis 5
Total no of elemenst in tensor tf.Tensor(120, shape=(), dtype=int32)
Total no of elemenst in tensor 120


Indexing the tensors

In [ ]:
# get first two elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the second last one
rank_4_tensor[:1, :1, :, :1]


<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
import numpy as np
import tensorflow as tf
npary = np.arange(1, 121, dtype = np.int32)
npary

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120], dtype=int32)

In [ ]:
rnk4tensor = tf.constant(npary, shape = (2,3,4, 5))
rnk4tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]], dtype=int32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rnk4tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[1, 2, 3, 4, 5]]]], dtype=int32)>

In [ ]:
# Get the first element from each dimension from each index except for the second last one
rnk4tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 6],
         [11],
         [16]]]], dtype=int32)>

In [ ]:
rnk4tensor[:2, :1, :1, :]

<tf.Tensor: shape=(2, 1, 1, 5), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4,  5]]],


       [[[61, 62, 63, 64, 65]]]], dtype=int32)>

In [ ]:
rnk4tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=int32, numpy=
array([[[[ 1]]],


       [[[61]]]], dtype=int32)>

In [ ]:
rnk4tensor[:, :3, :1, :1]

<tf.Tensor: shape=(2, 3, 1, 1), dtype=int32, numpy=
array([[[[  1]],

        [[ 21]],

        [[ 41]]],


       [[[ 61]],

        [[ 81]],

        [[101]]]], dtype=int32)>

In [ ]:
#adding extra diemsion in rnk4tensor

#lets create rank 2 tensor
rank2tensor = tf.constant([[1,2],
                           [3,4]])
rank2tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# get the last item of each row
rank2tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# now add extra diemsion
rank3tensor = rank2tensor[..., tf.newaxis]  # ... means all the previous axis [:, :, tf.newaxis]
rank3tensor  # so we got new axis, rows =1

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
#another way
tf.expand_dims(rank2tensor, axis = -1) # -1 expand the final axis  # only 1 column is output

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank2tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank2tensor, axis = 1)  # only 1 row in output

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

In [ ]:
# tensor remains same
rank2tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

# Manipulating the Tensors

In [ ]:
# Basic Operations, like add, substract.... python operations

tensor = tf.constant([[1, 2],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
# but original tensor remains unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
# multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Alternative we can use tf library functions
tf.multiply(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

When we use tensor lib operations, it works fast on GPU

In [ ]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 22],
       [23, 24]], dtype=int32)>

In [ ]:
tf.math.add(tensor, 10)  #same

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 22],
       [23, 24]], dtype=int32)>

Matrix Multiplication

In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[277, 300],
       [325, 352]], dtype=int32)>

In [ ]:
 tensor * tensor   # element wise

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121, 144],
       [169, 196]], dtype=int32)>

In [ ]:
tensor @ tensor # python matrix multiplication 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[277, 300],
       [325, 352]], dtype=int32)>

In [ ]:
a = tf.reshape( tensor, (1,4))
a

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[11, 12, 13, 14]], dtype=int32)>

In [ ]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8], [9, 10], [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

# Dot Product
***either use tf.matmult or tf.tensordot***


In [ ]:
tf.tensordot(tf.transpose(X), Y, axes =1)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes =0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[21, 24],
         [27, 30],
         [33, 36]],

        [[35, 40],
         [45, 50],
         [55, 60]]],


       [[[14, 16],
         [18, 20],
         [22, 24]],

        [[28, 32],
         [36, 40],
         [44, 48]],

        [[42, 48],
         [54, 60],
         [66, 72]]]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes =0).shape

TensorShape([2, 3, 3, 2])

In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

# Changing the Tensor Data Type

In [5]:
import tensorflow as tf
#create a tensor with default datatype
B = tf.constant([1.2, 2.3])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 2.3], dtype=float32)>

In [6]:
C = tf.constant([7, 10])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [7]:
#change float32 to float16
D = tf.cast(B, dtype= tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 2.3], dtype=float16)>

In [9]:
E = tf.cast(C, dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

# Aggregating Tensors

In [12]:
#Getting the absolute values
D =  tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [13]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [14]:
import numpy as np
E = tf.constant(np.random.randint(0, 100, size = 50))

In [15]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([58, 61, 91, 64, 59, 16, 98, 82, 54, 42, 43, 32,  7, 77, 36, 20, 50,
       87, 46, 99,  1, 63, 50, 85, 54, 14, 39, 45,  9,  5, 42, 29, 50, 55,
       61, 46, 60, 58, 43,  2, 12, 72, 35,  5, 12, 48, 88, 94, 18, 38])>

In [16]:
# find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [17]:
tf.reduce_max(E)  #max

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [18]:
#mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [19]:
#sum of all
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2355>

In [20]:
import tensorflow_probability as tfp
print(tfp.stats.variance(E))   #variance

tf.Tensor(728, shape=(), dtype=int64)


In [25]:
#std deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=27.0>

Positional Maximum and Minimum

In [32]:
tf.random.set_seed(1000)
F= tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.651229  , 0.7032492 , 0.9759028 , 0.45668054, 0.4284352 ,
       0.2098366 , 0.67993534, 0.08687031, 0.69594765, 0.78639126,
       0.05218327, 0.999194  , 0.01398969, 0.98920226, 0.63178253,
       0.7986791 , 0.09715199, 0.36159647, 0.2579999 , 0.60788894,
       0.37876713, 0.6883582 , 0.00567961, 0.82277584, 0.15667355,
       0.39339924, 0.15392876, 0.19924319, 0.11430919, 0.37630916,
       0.19842768, 0.24976063, 0.37064362, 0.22610748, 0.03673565,
       0.01211023, 0.20908308, 0.7338308 , 0.7928946 , 0.17541528,
       0.82539856, 0.5798024 , 0.8355168 , 0.6288792 , 0.45131278,
       0.22694528, 0.5034226 , 0.8982452 , 0.43032408, 0.7605754 ],
      dtype=float32)>

In [33]:
tf.argmax(F)  # so location is 11, i.e. 12th number

<tf.Tensor: shape=(), dtype=int64, numpy=11>

In [34]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.999194>

In [35]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.999194>

In [36]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=22>

Sqeezing the tensors(removing all single dimesions)

In [39]:
G = tf.constant(tf.random.uniform(shape =[50]), shape = (1,1,1,1,50))

In [40]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.830091  , 0.75588727, 0.71028507, 0.95232105, 0.1077354 ,
           0.11591995, 0.49214828, 0.5244429 , 0.50290906, 0.683617  ,
           0.5204675 , 0.8650211 , 0.86823606, 0.9794272 , 0.37881434,
           0.9946307 , 0.53842413, 0.7810657 , 0.312122  , 0.6996194 ,
           0.7313664 , 0.12863505, 0.20284736, 0.9472259 , 0.57367325,
           0.7283696 , 0.34171438, 0.46849144, 0.48287606, 0.16760659,
           0.5173696 , 0.24672973, 0.0493741 , 0.5353234 , 0.48866105,
           0.57031703, 0.11398757, 0.5705625 , 0.7624364 , 0.5879047 ,
           0.9050596 , 0.48443294, 0.80795944, 0.76823664, 0.17763054,
           0.27127075, 0.4318018 , 0.5752975 , 0.18418849, 0.6763425 ]]]]],
      dtype=float32)>

In [41]:
G_sqeezed = tf.squeeze(G)   # removes all single dimesions from the tensor
G_sqeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.830091  , 0.75588727, 0.71028507, 0.95232105, 0.1077354 ,
       0.11591995, 0.49214828, 0.5244429 , 0.50290906, 0.683617  ,
       0.5204675 , 0.8650211 , 0.86823606, 0.9794272 , 0.37881434,
       0.9946307 , 0.53842413, 0.7810657 , 0.312122  , 0.6996194 ,
       0.7313664 , 0.12863505, 0.20284736, 0.9472259 , 0.57367325,
       0.7283696 , 0.34171438, 0.46849144, 0.48287606, 0.16760659,
       0.5173696 , 0.24672973, 0.0493741 , 0.5353234 , 0.48866105,
       0.57031703, 0.11398757, 0.5705625 , 0.7624364 , 0.5879047 ,
       0.9050596 , 0.48443294, 0.80795944, 0.76823664, 0.17763054,
       0.27127075, 0.4318018 , 0.5752975 , 0.18418849, 0.6763425 ],
      dtype=float32)>

In [42]:
G_sqeezed.shape

TensorShape([50])

# One Hot Encoding
creating binary variable, one of the form of numerical encoding

In [43]:
some_list = [0, 1, 2, 3]
one_hot_encode = tf.one_hot(some_list, depth = 4)
one_hot_encode

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [44]:
some_list = [0, 1, 2, 3]
one_hot_encode = tf.one_hot(some_list, depth = 3)
one_hot_encode

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [45]:
some_list = [0, 1, 2, 3]
one_hot_encode = tf.one_hot(some_list, depth = 2)
one_hot_encode

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [46]:
some_list = [0, 1, 2, 3]
one_hot_encode = tf.one_hot(some_list, depth = 5)
one_hot_encode

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [47]:
#specify coustom values for one hot encoding
another= tf.one_hot(some_list, depth =4, on_value = "Abhishek", off_value = "How are you")
another

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Abhishek', b'How are you', b'How are you', b'How are you'],
       [b'How are you', b'Abhishek', b'How are you', b'How are you'],
       [b'How are you', b'How are you', b'Abhishek', b'How are you'],
       [b'How are you', b'How are you', b'How are you', b'Abhishek']],
      dtype=object)>

In [48]:
# squaring the tensor
H = tf.range(1,10)
print(H)
print(tf.square(H))

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor([ 1  4  9 16 25 36 49 64 81], shape=(9,), dtype=int32)


In [51]:
#Squareroot
tf.sqrt(tf.cast(H, dtype = tf.float32))  #works for real values, so we have to cast 


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [54]:
# Find the log
tf.math.log(tf.cast(H, dtype = tf.float32)) 

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>